strategy_params = {"directional_strategy_name": "MACD_DIFF_V1",
                   "trading_pair": "DOGE-BUSD",
                   "interval": "5m",
                   "exchange": "binance_perpetual",
                   "initial_portfolio": 150.0,
                   "start_timestamp": 1686754800000.0,
                   "order_amount_usd": 20.0,
                   "leverage": 20,
                   "stop_loss": 0.0075,
                   "take_profit": 0.1,
                   "time_limit": 60 * 55,
                   "trailing_stop_activation_delta": 0.0016,
                   "trailing_stop_trailing_delta": 0.001,
                   "delta_macd_thold": 0.0008,
                   "macdh_norm_thold": 0.0,
                   "target_thold": 0.0025}
