strategy_params = {"directional_strategy_name": "MACD_DIFF_V1",
                   "trading_pair": "DOGE-BUSD",
                   "interval": "5m",
                   "exchange": "binance_perpetual",
                   "initial_portfolio": 149.02,
                   "start_timestamp": 1687882093000.0,
                   "end_timestamp": 1688501738000.0,
                   "order_amount_usd": 20.0,
                   "leverage": 20,
                   "std_span": 100,
                   "stop_loss_multiplier": 0.3,
                   "take_profit_multiplier": 0.3,
                   "time_limit": 60 * 55,
                   "trailing_stop_activation_delta": 0.004,
                   "trailing_stop_trailing_delta": 0.002,
                   "delta_macd_thold": 0.0006,
                   "macdh_norm_thold": 0.0,
                   "target_thold": 0.0045}
